import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(scriptDir, "..");
const assetDir = path.join(webRoot, "public", "logos", "assets");
const outputDir = path.join(webRoot, "src", "lib", "generated");
const outputPath = path.join(outputDir, "assetLogoKeys.ts");

const assetLogoKeys = fs
  .readdirSync(assetDir, { withFileTypes: true })
  .filter((entry) => entry.isFile() && path.extname(entry.name) === ".svg")
  .map((entry) => path.basename(entry.name, ".svg"))
  .sort((left, right) => left.localeCompare(right));

const output = `${"// This file is auto-generated by apps/web/scripts/generate-asset-logo-manifest.ts.\n"}
export const ASSET_LOGO_KEYS = new Set<string>([\n${assetLogoKeys
  .map((key) => `  ${JSON.stringify(key)},`)
  .join("\n")}\n]);\n`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(outputPath, output);
